resources:
- name: paas-docker-cloudfoundry-tools
  type: git
  source:
    uri: https://github.com/alphagov/paas-docker-cloudfoundry-tools.git
    branch: main

- name: paas-tech-docs
  type: git
  source:
    uri: https://github.com/alphagov/paas-tech-docs.git
    branch: master

- name: paas-semver-resource
  type: git
  source:
    uri: https://github.com/alphagov/paas-semver-resource.git
    branch: gds_master

- name: paas-grafana-annotation-resource
  type: git
  source:
    uri: https://github.com/alphagov/paas-grafana-annotation-resource.git
    branch: main

- name: psql
  type: registry-image
  icon: docker
  source: &build-image-source
    username: ((dockerhub_username))
    password: ((dockerhub_password))
    repository: governmentpaas/psql

- name: spruce
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/spruce

- name: json-minify
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/json-minify

- name: terraform
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/terraform

- name: self-update-pipelines
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/self-update-pipelines

- name: git-ssh
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/git-ssh

- name: curl-ssl
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/curl-ssl

- name: cf-cli
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/cf-cli

- name: cf-acceptance-tests
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/cf-acceptance-tests

- name: cf-uaac
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/cf-uaac

- name: certstrap
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/certstrap

- name: bosh-cli-v2
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/bosh-cli-v2

- name: awscli
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/awscli

- name: tech-docs
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/tech-docs

- name: semver-resource
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/semver-resource

- name: grafana-annotation-resource
  type: registry-image
  icon: docker
  source:
    <<: *build-image-source
    repository: governmentpaas/grafana-annotation-resource

jobs:
- name: build-psql
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config: &build-image-config
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/psql
      inputs:
      - name: paas-docker-cloudfoundry-tools
      outputs:
      - name: image
      run:
        path: build
  - task: create-image-tag
    config: &create-image-tag
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: paas-docker-cloudfoundry-tools
      - name: image
      outputs:
      - name: image
      run:
        path: sh
        args:
          - -e
          - -u
          - -c
          - |
            git_branch_name="$(cd paas-docker-cloudfoundry-tools && \
                          git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

            git_commit_sha="$(cd paas-docker-cloudfoundry-tools && \
                     git log --pretty=format:'%H' -n 1)"

            echo "${git_branch_name} ${git_commit_sha}" > image/tags
  - put: psql
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-spruce
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/spruce
  - task: create-image-tag
    config: *create-image-tag
  - put: spruce
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-json-minify
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/json-minify
  - task: create-image-tag
    config: *create-image-tag
  - put: json-minify
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-terraform
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/terraform
  - task: create-image-tag
    config: *create-image-tag
  - put: terraform
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-self-update-pipelines
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/self-update-pipelines
  - task: create-image-tag
    config: *create-image-tag
  - put: self-update-pipelines
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-git-ssh
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/git-ssh
  - task: create-image-tag
    config: *create-image-tag
  - put: git-ssh
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-curl-ssl
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/curl-ssl
  - task: create-image-tag
    config: *create-image-tag
  - put: curl-ssl
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-cf-cli
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/cf-cli
  - task: create-image-tag
    config: *create-image-tag
  - put: cf-cli
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-cf-acceptance-tests
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/cf-acceptance-tests
  - task: create-image-tag
    config: *create-image-tag
  - put: cf-acceptance-tests
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-cf-uaac
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/cf-uaac
  - task: create-image-tag
    config: *create-image-tag
  - put: cf-uaac
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-certstrap
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/certstrap
  - task: create-image-tag
    config: *create-image-tag
  - put: certstrap
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-bosh-cli-v2
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/bosh-cli-v2
  - task: create-image-tag
    config: *create-image-tag
  - put: bosh-cli-v2
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-awscli
  plan:
  - get: paas-docker-cloudfoundry-tools
    trigger: true
  - task: build
    privileged: true
    config:
      <<: *build-image-config
      params:
        CONTEXT: paas-docker-cloudfoundry-tools/awscli
  - task: create-image-tag
    config: *create-image-tag
  - put: awscli
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-paas-tech-docs
  plan:
  - get: paas-tech-docs
    trigger: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: paas-tech-docs
        path: .
      outputs:
      - name: image
      run:
        path: build
  - put: tech-docs
    params:
      image: image/image.tar

- name: build-paas-semver-resource
  plan:
  - get: paas-semver-resource
    trigger: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: paas-semver-resource
        path: .
      outputs:
      - name: image
      run:
        path: build
  - task: create-image-tag
    config: &create-image-tag
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: paas-semver-resource
      - name: image
      outputs:
      - name: image
      run:
        path: sh
        args:
          - -e
          - -u
          - -c
          - |
            git_branch_name="$(cd paas-semver-resource && \
                          git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

            git_commit_sha="$(cd paas-semver-resource && \
                     git log --pretty=format:'%H' -n 1)"

            echo "${git_branch_name} ${git_commit_sha}" > image/tags
  - put: semver-resource
    params:
      image: image/image.tar
      additional_tags: image/tags

- name: build-paas-grafana-annotation-resource
  plan:
  - get: paas-grafana-annotation-resource
    trigger: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: paas-grafana-annotation-resource
        path: .
      outputs:
      - name: image
      run:
        path: build
  - task: create-image-tag
    config: &create-image-tag
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: paas-grafana-annotation-resource
      - name: image
      outputs:
      - name: image
      run:
        path: sh
        args:
          - -e
          - -u
          - -c
          - |
            git_branch_name="$(cd paas-grafana-annotation-resource && \
                          git rev-parse --abbrev-ref HEAD | sed -e 's/^/ /')"

            git_commit_sha="$(cd paas-grafana-annotation-resource && \
                     git log --pretty=format:'%H' -n 1)"

            echo "${git_branch_name} ${git_commit_sha}" > image/tags
  - put: grafana-annotation-resource
    params:
      image: image/image.tar
      additional_tags: image/tags
