---
resource_types:
  - name: slack-notification-resource
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: paas-product-pages
    type: git
    check_every: 1m
    source:
      uri: https://github.com/alphagov/paas-product-pages.git
      branch: master

  - name: slack-notification
    type: slack-notification-resource
    source:
      url: ((slack_webhook_url))

jobs:
  - name: deploy
    serial: true

    on_failure:
      put: slack-notification
      params:
        text: "Job $BUILD_NAME in $BUILD_JOB_NAME on $BUILD_PIPELINE_NAME failed. Check the logs at $ATC_EXTERNAL_URL/builds/$BUILD_ID."

    plan:
      - get: paas-product-pages
        trigger: true

      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: lts
          inputs:
            - name: paas-product-pages
          outputs:
            - name: paas-product-pages
          run:
            dir: paas-product-pages
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                npm install
                node "$(npm bin)/rollup" -c && node "$(npm bin)/next" build && node "$(npm bin)/next" export

      - task: push
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: b9a032b6ca185690bd679e1802e6b7af6a2bc43a
          inputs:
            - name: paas-product-pages
          params:
            CF_API: https://api.((cf_system_domain))
            CF_USER: ((cf_user))
            CF_PASSWORD: ((cf_password))
            CF_APPS_DOMAIN: ((cf_apps_domain))
            CF_SYSTEM_DOMAIN: ((cf_system_domain))
            CF_ORG: govuk-paas
            CF_SPACE: docs
          run:
            dir: paas-product-pages
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                echo "Logging on to Cloudfoundry..."
                cf login \
                  -a "${CF_API}" \
                  -u "${CF_USER}" \
                  -p "${CF_PASSWORD}" \
                  -o "${CF_ORG}" \
                  -s "${CF_SPACE}"

                cf cancel-deployment paas-product-pages || true
                cf push paas-product-pages --strategy=rolling
