---
resource_types:
  - name: s3-iam
    type: docker-image
    check_every: 24h
    source:
      repository: governmentpaas/s3-resource
      tag: 97e441efbfb06ac7fb09786fd74c64b05f9cc907

  - name: semver-iam
    type: docker-image
    check_every: 24h
    source:
      repository: ghcr.io/alphagov/paas/semver-resource
      tag: f2a80c95481056aa57d837e3b14f0012b542fdb3

resources:
  - name: pipeline-trigger
    type: semver-iam
    check_every: 24h
    source:
      bucket: ((state_bucket_name))
      region_name: ((aws_region))
      key: ((pipeline_trigger_file))

  - name: paas-release-ci
    type: git
    check_every: 1m
    source:
      uri: https://github.com/alphagov/paas-release-ci
      branch: ((branch_name))

  - name: release-ci-tfstate
    type: s3-iam
    check_every: 24h
    source:
      bucket: ((state_bucket_name))
      region_name: ((aws_region))
      versioned_file: release-ci.tfstate

jobs:
  - name: init
    plan:
      - put: pipeline-trigger
        params: {bump: patch}

  - name: terraform-destroy
    plan:
      - in_parallel:
          - get: pipeline-trigger
            passed: ['init']
            trigger: true
          - get: paas-release-ci
          - get: release-ci-tfstate
      - task: terraform-destroy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ghcr.io/alphagov/paas/terraform
              tag: 90f9f534ed5a3887b9c5d55a20cca6561f7de6a4
          inputs:
            - name: paas-release-ci
            - name: release-ci-tfstate
          outputs:
            - name: updated-release-ci-tfstate
          params:
            TF_VAR_deploy_env: ((deploy_env))
            TF_VAR_releases_bucket_name: ((releases_bucket_name))
            TF_VAR_releases_blobs_bucket_name: ((releases_blobs_bucket_name))
          run:
            path: sh
            args:
              - -e
              - -u
              - -c
              - |
                cp release-ci-tfstate/release-ci.tfstate updated-release-ci-tfstate/release-ci.tfstate
                terraform init paas-release-ci/terraform
                terraform destroy -force \
                  -state=updated-release-ci-tfstate/release-ci.tfstate \
                  paas-release-ci/terraform
        ensure:
          put: release-ci-tfstate
          params:
            file: updated-release-ci-tfstate/release-ci.tfstate
