---
resource_types:
  - name: pull-request
    type: docker-image
    check_every: 24h
    source:
      repository: teliaoss/github-pr-resource
      tag: v0.21.0

  - name: s3-iam
    type: docker-image
    check_every: 24h
    source:
      repository: governmentpaas/s3-resource
      tag: 97e441efbfb06ac7fb09786fd74c64b05f9cc907

resources:
  - name: pr
    type: pull-request
    check_every: 1m
    source:
      repository: ((github_repo))
      access_token: ((github_access_token))
      disable_forks: true

  - name: release-repository
    type: git
    check_every: 1m
    source:
      branch: ((tag_branch))
      ignore_paths:
        - ((version_file))
      private_key: ((tagging_key))
      uri: ((github_repo_uri))

  - name: resource-version
    type: semver
    check_every: 24h
    source:
      branch: ((tag_branch))
      driver: git
      file: ((version_file))
      git_user: "GovUK-PaaS-CI-User <the-multi-cloud-paas-team+ci-github-user@digital.cabinet-office.gov.uk>"
      initial_version: 0.0.1
      private_key: ((tagging_key))
      uri: ((github_repo_uri))

jobs:
  - name: integration-test
    serial: true
    plan:
      - get: repo
        resource: pr
        version: every
        trigger: true
        params:
          integration_tool: checkout
      - put: repo
        resource: pr
        params:
          path: repo
          context: ((github_status_context))
          status: pending
        get_params:
          skip_download: true
      - task: run-tests
        file: repo/ci/integration.yml
    on_success:
      put: repo
      resource: pr
      params:
        path: repo
        context: ((github_status_context))
        status: success
      get_params:
        skip_download: true
    on_failure:
      put: repo
      resource: pr
      params:
        path: repo
        context: ((github_status_context))
        status: failure
      get_params:
        skip_download: true

  - name: tag-releases
    serial: true
    plan:
    - get: repo
      resource: release-repository
      trigger: true
    - get: resource-version
      params:
        bump: minor
    - task: run-tests
      file: repo/ci/integration.yml
      on_success:
        put: resource-version
        params:
          file: resource-version/number
    on_success:
      put: release-repository
      params:
        only_tag: true
        repository: repo
        tag: resource-version/number
        tag_prefix: "v"
