---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: paas-example-boshrelease
    type: pull-request
    source:
      repo: richardc/paas-example-boshrelease
      access_token: {{access_token}}

jobs:
  - name: paas-example-boshrelease-pullrequests
    plan:
    - get: paas-example-boshrelease
      trigger: true
    - put: paas-example-boshrelease
      params:
        path: paas-example-boshrelease
        status: pending
    - task: build
      config:
        platform: linux
        image: docker:///concourse/git-resource
        inputs:
          - name: paas-example-boshrelease
        run:
          path: sh
          args:
            - -e
            - -c
            - |
              ls -al
              exit 1
      on_success:
        put: paas-example-boshrelease
        params:
          path: paas-example-boshrelease
          status: success
      on_failure:
        put: paas-example-boshrelease
        params:
          path: paas-example-boshrelease
          status: failure
